version: '2.3'
services:
        db:
                image: postgres
                restart: always
                volumes:
                        - ./initdb:/docker-entrypoint-initdb.d
                environment:
                        POSTGRES_PASSWORD: toor
                        POSTGRES_USER: root
                networks:
                        nakernet:
                                ipv4_address: 192.168.1.2


        app:
                build:
                        context: .
                        dockerfile: php-server-dockerfile
                restart: always
                volumes:
                        - ./web-application:/var/www/html
                        - ./config/php.ini:/usr/local/etc/php/php.ini
                ports:
                        - "8081:80"
                dns:
                        - "8.8.8.8"
                networks:
                        nakernet:
                                ipv4_address: 192.168.1.3

networks:
       nakernet:
               driver: bridge
               ipam:
                        config:
                               - subnet: 192.168.1.0/24
